---
version: "3"

vars:
  PROJECT: machinery-registry-api
  MODULE: github.com/stuttgart-things/machinery-registry-api
  BIN_DIR: ./bin

includes:
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/git.yaml
  lint:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/linting.yaml
  go:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/go/lint.yaml

tasks:
  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove only trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"

  build:
    desc: Build the binary
    cmds:
      - go build -o {{.BIN_DIR}}/{{.PROJECT}} .

  run:
    desc: Run the application
    cmds:
      - go run .

  test:
    desc: Run tests
    cmds:
      - go test ./...

  fmt:
    desc: Format code
    cmds:
      - gofmt -s -w .

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy
